#!/bin/bash

function compruebaDirectorios (){

	if [ -d /srv/gitlab/config ] ; then 
	echo Ruta existente
	else mkdir -p /srv/gitlab/config
	fi
	
	if [ -d /srv/gitlab/data ] ; then
	echo Ruta existente
	else mkdir -p /srv/gitlab/data
	fi
}

compruebaDirectorios

sudo docker run --detach \
	--hostname gitlab \
	--publish 443:443 --publish 80:80 --publish 28:22 \
	--name gitlab \
	--restart always \
	--volume /srv/gitlab/config:/etc/gitlab \
	--volume /srv/gitlab/logs:/var/log/gitlab \
	--volume /srv/gitlab/data:/var/opt/gitlab \
	gitlab/gitlab-ce:latest
	


