#!/bin/bash

function compruebaDirectorios (){
	directories=(config data logs)
	
	for directory in ${directories[@]}; do
		mkdir -p /srv/gitlab/${directory}
	done
}

compruebaDirectorios

sudo docker run --detach \
	--hostname gitlab \
	--publish 443:443 --publish 80:80 --publish 28:22 \
	--name gitlab \
	--restart always \
	--volume /srv/gitlab/config:/etc/gitlab:rw \
	--volume /srv/gitlab/logs:/var/log/gitlab:rw \
	--volume /srv/gitlab/data:/var/opt/gitlab:rw \
	gitlab/gitlab-ce:latest
